[versions]
kotlin-language = "1.9.25"
spring-boot = "3.3.3"
spring-dependency-management = "1.1.6"
ktlint = "12.1.1"
kotlin-logging = "7.0.0"
assertj = "3.26.3"
instancio = "5.0.1"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-oauth2-resourceserver = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
liquibase-core = { group = "org.liquibase", name = "liquibase-core" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
postgres = { group = "org.postgresql", name = "postgresql" }

assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
instancio = { group = "org.instancio", name = "instancio-junit", version.ref = "instancio" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }

spring-boot-docker-compose = { group = "org.springframework.boot", name = "spring-boot-docker-compose" }

[bundles]
testing = [
    "kotlin-test-junit5",
    "instancio",
    "assertj"
]